sudo: required
services:
  - docker

before_install:
  - docker build -t kidnohr2000/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run  -e "CI=true" kidnohr2000/react-test npm test -- --coverage

after_success:
  - docker build -t kidnohr2000/multi-client ./client/Dockerfile ./client
  - docker build -t kidnohr2000/multi-nginx ./nginx/Dockerfile ./nginx
  - docker build -t kidnohr2000/multi-server ./server/Dockerfile ./server
  - docker build -t kidnohr2000/multi-worker ./worker/Dockerfile ./worker
  # Log in docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push Image
  - docker push kidnohr2000/multi-client
  - docker push kidnohr2000/multi-nginx
  - docker push kidnohr2000/multi-server
  - docker push kidnohr2000/multi-worker